### ISSUE TITLE
[0.4.3] Intro Cutscene Black Screen

### ISSUE THREAD

**Issue by SirBlockles** [Galster2010/CrowdedSheriff#6]
CrowdedSheriff 0.4.3 - occurs with or without CrowdedMod
Occurs with both Reactor's Bepin, as well as the one packaged with the mod itself on the CurseForge release.

Some clients' screens will freeze during the role reveal with the following error logged:
```
[Error  :    Detour] System.MissingMethodException: Method not found: PENEIDJGGAF .CKACLKCOJFO.get_field_Public_PENEIDJGGAF_0()
  at (wrapper dynamic-method) PENEIDJGGAF+CKACLKCOJFO.DMD<PENEIDJGGAF+CKACLKCOJFO::MoveNext>(PENEIDJGGAF/CKACLKCOJFO)
  at (wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.(il2cpp -> managed) MoveNext(intptr,UnhollowerBaseLib.Runtime.Il2CppMethodInfo*)
```
Once the game ends, the victory/defeat screen will show properly and players can return to the game lobby as normal.
![Among_Us_2021-02-06_12-02-02](https://user-images.githubusercontent.com/3620019/107127595-65e60300-6874-11eb-9208-0099907162dc.png)

**Comment by Galster-dev** [comment]
Can you provide full log file, OS, game version and its platform?

**Comment by SirBlockles** [comment]
Turns out that I had some weird remnant file from a different bepin install that was being loaded by the proven-good version of bepin, and reinstalling 100% fresh fixed it.
